// Interactive Brokers Flex Web Service → ledger rows. Pure functions.
// Flex reports are XML generated by IBKR: attributes are always double-quoted and escaped, so a small regex reader
// is enough (Node has no XML parser built in). ponytail: fine for IBKR's generated files, not for arbitrary XML.
import { addDays } from '../engine/index.js'

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" }
const unescape = s => s.replace(/&(amp|lt|gt|quot|apos|#\d+);/g, (_, e) => ENTITIES[e] ?? String.fromCharCode(Number(e.slice(1))))
const attributes = tag => Object.fromEntries([...tag.matchAll(/([\w:]+)="([^"]*)"/g)].map(([, k, v]) => [k, unescape(v)]))
const text = (xml, name) => xml.match(new RegExp(`<${name}>([^<]*)</${name}>`))?.[1]?.trim()

// The answer of SendRequest, or of GetStatement when the statement isn't ready: { ok, referenceCode } or { ok: false, code, message }
export function parseFlexStatus(xml) {
  if (!/<FlexStatementResponse\b/.test(xml)) return null // Not a status answer: the statement itself
  if (text(xml, 'Status') === 'Success') return { ok: true, referenceCode: text(xml, 'ReferenceCode') }
  return { ok: false, code: Number(text(xml, 'ErrorCode')), message: text(xml, 'ErrorMessage') ?? '' }
}

// Every <Trade …/> of a FlexQueryResponse, as attribute objects
export function parseTrades(xml) {
  if (!/<FlexQueryResponse\b/.test(xml)) throw new Error('IB 回傳的不是 XML 格式的 Flex 報表，請把 Flex Query 的格式設成 XML')
  return [...xml.matchAll(/<Trade\s([^>]*?)\/?>/g)].map(([, tag]) => attributes(tag))
}

// The accounts a statement covers
export const parseAccounts = xml => [...xml.matchAll(/<FlexStatement\s([^>]*)>/g)].map(([, tag]) => attributes(tag).accountId)

// The central bank's daily NT$ per US$ (cpx.cbc.gov.tw, BP01D01) → [[date, rate], …] oldest first
export function parseCbcRates(json) {
  const columns = json?.data?.structure?.Table1 ?? []
  const col = columns.findIndex(c => /NTD\/USD/.test(c.data)) + 1 // The first cell of each row is the date
  if (!col) throw new Error('中央銀行的匯率資料格式變了，找不到新台幣兌美元')
  return (json.data.dataSets ?? [])
    .map(([d, ...cells]) => [`${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}`, Number(cells[col - 1])])
    .filter(([date, rate]) => /^\d{4}-\d{2}-\d{2}$/.test(date) && rate > 0)
    .sort(([a], [b]) => a.localeCompare(b))
}

// fd/td date ranges for SendRequest: at most 365 days each
export function flexWindows(from, to) {
  const windows = []
  for (let start = from; start <= to; start = addDays(start, 365)) {
    const end = addDays(start, 364) < to ? addDays(start, 364) : to
    windows.push([start.replaceAll('-', ''), end.replaceAll('-', '')])
  }
  return windows
}

const isoDate = s => {
  const d = String(s ?? '').split(/[;, ]/)[0] // "20250915" or "2025-09-15", sometimes with a time after it
  const m = d.match(/^(\d{4})-?(\d{2})-?(\d{2})$/)
  return m ? `${m[1]}-${m[2]}-${m[3]}` : null
}
const number = s => Math.abs(Number.parseFloat(String(s ?? '').replace(/,/g, ''))) || 0

// Executions of US-dollar stocks and ETFs → ledger rows in NT$, converted with the central bank's rate of the trade date
// (the last one published on or before it). A trade newer than the latest published rate waits for the next sync, so its
// amount never changes once written (a changed amount would look like a second trade).
export function toRows(trades, rates, from, to) {
  const rows = [], skipped = { currency: new Set(), category: new Set(), date: 0 }
  let waiting = 0
  const latest = rates.at(-1)?.[0]
  const rateOn = date => {
    let lo = 0, hi = rates.length - 1, found = null
    while (lo <= hi) { // The last rate on or before the date
      const mid = (lo + hi) >> 1
      if (rates[mid][0] <= date) { found = rates[mid][1]; lo = mid + 1 } else hi = mid - 1
    }
    return found
  }
  // Only executions: a query that also lists orders or closed lots would count the same shares twice.
  // Only stocks and ETFs (STK): options, futures, forex… are named in a warning
  const executions = trades.filter(t => !t.levelOfDetail || t.levelOfDetail === 'EXECUTION')
  for (const t of executions) if (t.assetCategory !== 'STK') skipped.category.add(t.assetCategory)
  const stocks = executions.filter(t => t.assetCategory === 'STK')
  // IBKR lists a cancelled execution twice: the original, and a "BUY (Ca.)" or "SELL (Ca.)" entry pointing at it with
  // origTradeID. Both are left out; without the ID, the original is found by symbol, date, quantity and price
  const isCancel = t => /\(Ca\.\)/.test(t.buySell ?? '')
  const cancels = stocks.filter(isCancel)
  const cancelledIds = new Set(cancels.map(t => t.origTradeID).filter(Boolean))
  const key = (t, orig) => [t.symbol, isoDate((orig && t.origTradeDate) || t.tradeDate), number(t.quantity), number((orig && t.origTradePrice) || t.tradePrice)].join('|')
  const cancelledKeys = cancels.filter(t => !t.origTradeID).map(t => key(t, true))
  for (const t of stocks) {
    if (isCancel(t) || (t.buySell !== 'BUY' && t.buySell !== 'SELL')) continue
    if (cancelledIds.has(t.tradeID)) continue
    const k = cancelledKeys.indexOf(key(t))
    if (k >= 0) {
      cancelledKeys.splice(k, 1)
      continue
    }
    const date = isoDate(t.tradeDate)
    if (!date) { skipped.date++; continue }
    if (date < from || date > to) continue
    if (t.currency !== 'USD') { skipped.currency.add(t.currency); continue }
    if (!latest || date > latest) { waiting++; continue }
    const rate = rateOn(date)
    const shares = number(t.quantity)
    if (!rate || !shares) continue
    const usd = number(t.proceeds) || shares * number(t.tradePrice)
    rows.push({
      date,
      symbol: String(t.symbol).trim().toUpperCase().replace(/\s+/g, '.'), // IBKR writes class shares as "BRK B"
      action: t.buySell === 'BUY' ? 'buy' : 'sell',
      shares,
      amount: Math.round(usd * rate),
      fee: Math.round((number(t.ibCommission) + number(t.taxes)) * rate),
    })
  }
  const warnings = []
  if (waiting) warnings.push(`${waiting} 筆最近的交易還等不到中央銀行公布當天匯率，之後同步會補上`)
  if (skipped.category.size) warnings.push(`略過股票與 ETF 以外的成交（${[...skipped.category].join('、')}）`)
  if (skipped.currency.size) warnings.push(`略過非美元的交易（${[...skipped.currency].join('、')}），NestEgg 目前只換算美元`)
  // A cancellation can arrive after the original was already written by an earlier sync, which merges and never deletes
  if (cancels.length) {
    const list = cancels.map(t => `${isoDate(t.origTradeDate || t.tradeDate)} ${t.symbol}`).join('、')
    warnings.push(`IB 取消了 ${cancels.length} 筆成交（${list}），這次不記；如果之前的同步已經記進帳本，請手動刪掉那一筆`)
  }
  if (skipped.date) warnings.push(`有 ${skipped.date} 筆交易的日期看不懂，請把 Flex Query 的日期格式設成 yyyyMMdd`)
  return { rows, warnings }
}
